"""Add lanes and lane_assignments for production scheduling

Revision ID: 59a3603c568e
Revises: e23072a55c9e
Create Date: 2025-11-09 13:31:27.644199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59a3603c568e'
down_revision = 'e23072a55c9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lanes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('lane_code', sa.String(length=50), nullable=False),
    sa.Column('lane_name', sa.String(length=200), nullable=False),
    sa.Column('capacity_per_day', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('capacity_per_day > 0', name='check_capacity'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'lane_code', name='uq_lane_code_per_plant')
    )
    op.create_index('idx_lane_active', 'lanes', ['is_active'], unique=False)
    op.create_index('idx_lane_plant', 'lanes', ['plant_id'], unique=False)
    op.create_index(op.f('ix_lanes_plant_id'), 'lanes', ['plant_id'], unique=False)
    op.create_table('lane_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('lane_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_start', sa.Date(), nullable=False),
    sa.Column('scheduled_end', sa.Date(), nullable=False),
    sa.Column('allocated_capacity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='laneassignmentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('allocated_capacity > 0', name='check_allocated_capacity'),
    sa.CheckConstraint('scheduled_end >= scheduled_start', name='check_dates'),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lane_assign_lane_dates', 'lane_assignments', ['lane_id', 'scheduled_start', 'scheduled_end'], unique=False)
    op.create_index('idx_lane_assign_org', 'lane_assignments', ['organization_id'], unique=False)
    op.create_index('idx_lane_assign_plant', 'lane_assignments', ['plant_id'], unique=False)
    op.create_index('idx_lane_assign_project', 'lane_assignments', ['project_id'], unique=False, postgresql_where=sa.text('project_id IS NOT NULL'))
    op.create_index('idx_lane_assign_status', 'lane_assignments', ['status'], unique=False)
    op.create_index('idx_lane_assign_wo', 'lane_assignments', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_lane_assignments_organization_id'), 'lane_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lane_assignments_plant_id'), 'lane_assignments', ['plant_id'], unique=False)
    op.create_index(op.f('ix_lane_assignments_status'), 'lane_assignments', ['status'], unique=False)
    op.alter_column('production_logs', 'custom_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('production_logs_timestamp_idx'), table_name='production_logs')
    op.create_index(op.f('ix_production_logs_timestamp'), 'production_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_logs_timestamp'), table_name='production_logs')
    op.create_index(op.f('production_logs_timestamp_idx'), 'production_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('production_logs', 'custom_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_lane_assignments_status'), table_name='lane_assignments')
    op.drop_index(op.f('ix_lane_assignments_plant_id'), table_name='lane_assignments')
    op.drop_index(op.f('ix_lane_assignments_organization_id'), table_name='lane_assignments')
    op.drop_index('idx_lane_assign_wo', table_name='lane_assignments')
    op.drop_index('idx_lane_assign_status', table_name='lane_assignments')
    op.drop_index('idx_lane_assign_project', table_name='lane_assignments', postgresql_where=sa.text('project_id IS NOT NULL'))
    op.drop_index('idx_lane_assign_plant', table_name='lane_assignments')
    op.drop_index('idx_lane_assign_org', table_name='lane_assignments')
    op.drop_index('idx_lane_assign_lane_dates', table_name='lane_assignments')
    op.drop_table('lane_assignments')
    op.drop_index(op.f('ix_lanes_plant_id'), table_name='lanes')
    op.drop_index('idx_lane_plant', table_name='lanes')
    op.drop_index('idx_lane_active', table_name='lanes')
    op.drop_table('lanes')
    # ### end Alembic commands ###
