"""Add multi-tenancy tables (organizations, plants, departments)

Revision ID: 2fd042a8a882
Revises: 37b0164d0ef3
Create Date: 2025-11-09 11:39:09.880268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd042a8a882'
down_revision = '37b0164d0ef3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_code', sa.String(length=20), nullable=False),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_index('idx_org_active', 'organizations', ['is_active'], unique=False)
    op.create_index('idx_org_code', 'organizations', ['org_code'], unique=False)
    op.create_index(op.f('ix_organizations_org_code'), 'organizations', ['org_code'], unique=True)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=20), nullable=False),
    sa.Column('plant_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_code', name='uq_plant_code_per_org')
    )
    op.create_index('idx_plant_active', 'plants', ['is_active'], unique=False)
    op.create_index('idx_plant_org', 'plants', ['organization_id'], unique=False)
    op.create_index('idx_plant_org_code', 'plants', ['organization_id', 'plant_code'], unique=False)
    op.create_index(op.f('ix_plants_organization_id'), 'plants', ['organization_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(length=20), nullable=False),
    sa.Column('dept_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'dept_code', name='uq_dept_code_per_plant')
    )
    op.create_index('idx_dept_active', 'departments', ['is_active'], unique=False)
    op.create_index('idx_dept_plant', 'departments', ['plant_id'], unique=False)
    op.create_index(op.f('ix_departments_plant_id'), 'departments', ['plant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_plant_id'), table_name='departments')
    op.drop_index('idx_dept_plant', table_name='departments')
    op.drop_index('idx_dept_active', table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_plants_organization_id'), table_name='plants')
    op.drop_index('idx_plant_org_code', table_name='plants')
    op.drop_index('idx_plant_org', table_name='plants')
    op.drop_index('idx_plant_active', table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_organizations_org_code'), table_name='organizations')
    op.drop_index('idx_org_code', table_name='organizations')
    op.drop_index('idx_org_active', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
