"""Initial schema with existing models - fixed index names

Revision ID: 37b0164d0ef3
Revises: 
Create Date: 2025-11-09 11:37:34.568597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b0164d0ef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('decimal_places <= 6', name='chk_decimal_places_max'),
    sa.CheckConstraint('decimal_places >= 0', name='chk_decimal_places_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_currency_code', 'currency', ['code'], unique=False)
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('machine_code', sa.String(length=20), nullable=False),
    sa.Column('machine_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_center_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RUNNING', 'IDLE', 'DOWN', 'SETUP', 'MAINTENANCE', name='machinestatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_machine_org_plant', 'machine', ['organization_id', 'plant_id'], unique=False)
    op.create_index('idx_machine_status', 'machine', ['status'], unique=False)
    op.create_index('idx_machine_work_center', 'machine', ['work_center_id'], unique=False)
    op.create_index(op.f('ix_machine_id'), 'machine', ['id'], unique=False)
    op.create_index(op.f('ix_machine_machine_code'), 'machine', ['machine_code'], unique=True)
    op.create_index(op.f('ix_machine_organization_id'), 'machine', ['organization_id'], unique=False)
    op.create_index(op.f('ix_machine_plant_id'), 'machine', ['plant_id'], unique=False)
    op.create_index(op.f('ix_machine_work_center_id'), 'machine', ['work_center_id'], unique=False)
    op.create_table('material_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=20), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['material_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'category_code', name='uq_category_code_per_org')
    )
    op.create_index('idx_material_category_org_code', 'material_category', ['organization_id', 'category_code'], unique=False)
    op.create_index(op.f('ix_material_category_category_code'), 'material_category', ['category_code'], unique=False)
    op.create_index(op.f('ix_material_category_id'), 'material_category', ['id'], unique=False)
    op.create_index(op.f('ix_material_category_organization_id'), 'material_category', ['organization_id'], unique=False)
    op.create_table('rework_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('default_rework_mode', sa.Enum('CONSUME_ADDITIONAL_MATERIALS', 'REPROCESS_EXISTING_WIP', 'HYBRID', name='reworkmode'), nullable=False),
    sa.Column('require_reason_code', sa.Boolean(), nullable=False),
    sa.Column('allow_multiple_rework_cycles', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', name='uq_rework_config_per_plant')
    )
    op.create_index('idx_rework_config_org_plant', 'rework_config', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_rework_config_organization_id'), 'rework_config', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rework_config_plant_id'), 'rework_config', ['plant_id'], unique=False)
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=100), nullable=False),
    sa.Column('shift_code', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('production_target', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('production_target >= 0', name='check_production_target_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'shift_code', name='uq_shift_code_per_plant')
    )
    op.create_index('idx_shift_active', 'shift', ['is_active'], unique=False)
    op.create_index('idx_shift_org_plant', 'shift', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_shift_organization_id'), 'shift', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shift_plant_id'), 'shift', ['plant_id'], unique=False)
    op.create_index(op.f('ix_shift_shift_code'), 'shift', ['shift_code'], unique=False)
    op.create_table('storage_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=20), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('location_type', sa.Enum('WAREHOUSE', 'PRODUCTION', 'QUALITY', 'BLOCKED', name='locationtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'location_code', name='uq_location_code_per_plant')
    )
    op.create_index('idx_storage_location_org_plant', 'storage_location', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_storage_location_id'), 'storage_location', ['id'], unique=False)
    op.create_index(op.f('ix_storage_location_location_code'), 'storage_location', ['location_code'], unique=False)
    op.create_index(op.f('ix_storage_location_organization_id'), 'storage_location', ['organization_id'], unique=False)
    op.create_index(op.f('ix_storage_location_plant_id'), 'storage_location', ['plant_id'], unique=False)
    op.create_table('unit_of_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uom_code', sa.String(length=10), nullable=False),
    sa.Column('uom_name', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Enum('LENGTH', 'MASS', 'VOLUME', 'TIME', 'QUANTITY', name='dimensiontype'), nullable=False),
    sa.Column('is_base_unit', sa.Boolean(), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_of_measure_id'), 'unit_of_measure', ['id'], unique=False)
    op.create_index(op.f('ix_unit_of_measure_uom_code'), 'unit_of_measure', ['uom_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('work_center',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('work_center_code', sa.String(length=20), nullable=False),
    sa.Column('work_center_name', sa.String(length=100), nullable=False),
    sa.Column('work_center_type', sa.Enum('MACHINE', 'ASSEMBLY', 'PACKAGING', 'QUALITY_CHECK', name='workcentertype'), nullable=False),
    sa.Column('capacity_per_hour', sa.Float(), nullable=False),
    sa.Column('cost_per_hour', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('capacity_per_hour > 0', name='check_capacity_positive'),
    sa.CheckConstraint('cost_per_hour >= 0', name='check_cost_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'work_center_code', name='uq_work_center_code_per_plant')
    )
    op.create_index('idx_work_center_org_plant', 'work_center', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_work_center_organization_id'), 'work_center', ['organization_id'], unique=False)
    op.create_index(op.f('ix_work_center_plant_id'), 'work_center', ['plant_id'], unique=False)
    op.create_index(op.f('ix_work_center_work_center_code'), 'work_center', ['work_center_code'], unique=False)
    op.create_table('downtime_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('BREAKDOWN', 'PLANNED_MAINTENANCE', 'CHANGEOVER', 'NO_OPERATOR', 'MATERIAL_SHORTAGE', name='downtimecategory'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_downtime_event_category', 'downtime_event', ['category'], unique=False)
    op.create_index('idx_downtime_event_machine', 'downtime_event', ['machine_id'], unique=False)
    op.create_index('idx_downtime_event_machine_time', 'downtime_event', ['machine_id', 'started_at'], unique=False)
    op.create_index('idx_downtime_event_org_plant', 'downtime_event', ['organization_id', 'plant_id'], unique=False)
    op.create_index('idx_downtime_event_time_range', 'downtime_event', ['started_at', 'ended_at'], unique=False)
    op.create_index(op.f('ix_downtime_event_category'), 'downtime_event', ['category'], unique=False)
    op.create_index(op.f('ix_downtime_event_ended_at'), 'downtime_event', ['ended_at'], unique=False)
    op.create_index(op.f('ix_downtime_event_id'), 'downtime_event', ['id'], unique=False)
    op.create_index(op.f('ix_downtime_event_machine_id'), 'downtime_event', ['machine_id'], unique=False)
    op.create_index(op.f('ix_downtime_event_organization_id'), 'downtime_event', ['organization_id'], unique=False)
    op.create_index(op.f('ix_downtime_event_plant_id'), 'downtime_event', ['plant_id'], unique=False)
    op.create_index(op.f('ix_downtime_event_started_at'), 'downtime_event', ['started_at'], unique=False)
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency_code', sa.String(length=3), nullable=False),
    sa.Column('to_currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_currency_code != to_currency_code', name='chk_different_currencies'),
    sa.CheckConstraint('rate > 0', name='chk_rate_positive'),
    sa.ForeignKeyConstraint(['from_currency_code'], ['currency.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_currency_code'], ['currency.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exchange_rate_currencies', 'exchange_rate', ['from_currency_code', 'to_currency_code'], unique=False)
    op.create_index('idx_exchange_rate_effective_date', 'exchange_rate', ['effective_date'], unique=False)
    op.create_index('idx_exchange_rate_lookup', 'exchange_rate', ['from_currency_code', 'to_currency_code', 'effective_date'], unique=False)
    op.create_index(op.f('ix_exchange_rate_effective_date'), 'exchange_rate', ['effective_date'], unique=False)
    op.create_index(op.f('ix_exchange_rate_from_currency_code'), 'exchange_rate', ['from_currency_code'], unique=False)
    op.create_index(op.f('ix_exchange_rate_id'), 'exchange_rate', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_rate_to_currency_code'), 'exchange_rate', ['to_currency_code'], unique=False)
    op.create_table('machine_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RUNNING', 'IDLE', 'DOWN', 'SETUP', 'MAINTENANCE', name='machinestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_machine_status_history_machine_time', 'machine_status_history', ['machine_id', 'started_at'], unique=False)
    op.create_index('idx_machine_status_history_time_range', 'machine_status_history', ['started_at', 'ended_at'], unique=False)
    op.create_index(op.f('ix_machine_status_history_ended_at'), 'machine_status_history', ['ended_at'], unique=False)
    op.create_index(op.f('ix_machine_status_history_id'), 'machine_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_machine_status_history_machine_id'), 'machine_status_history', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_status_history_started_at'), 'machine_status_history', ['started_at'], unique=False)
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('material_number', sa.String(length=10), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('material_category_id', sa.Integer(), nullable=False),
    sa.Column('base_uom_id', sa.Integer(), nullable=False),
    sa.Column('procurement_type', sa.Enum('PURCHASE', 'MANUFACTURE', 'BOTH', name='procurementtype'), nullable=False),
    sa.Column('mrp_type', sa.Enum('MRP', 'REORDER', name='mrptype'), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('lot_sizing_rule', sa.Enum('LOT_FOR_LOT', 'FIXED_LOT_SIZE', 'EOQ', 'POQ', name='lotsizingrule'), nullable=False),
    sa.Column('fixed_lot_size', sa.Float(), nullable=True),
    sa.Column('poq_period_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='poqperiodtype'), nullable=True),
    sa.Column('poq_periods_to_cover', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['base_uom_id'], ['unit_of_measure.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_category_id'], ['material_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_material_category', 'material', ['material_category_id'], unique=False)
    op.create_index('idx_material_number', 'material', ['material_number'], unique=False)
    op.create_index('idx_material_org_plant', 'material', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_material_id'), 'material', ['id'], unique=False)
    op.create_index(op.f('ix_material_material_number'), 'material', ['material_number'], unique=True)
    op.create_index(op.f('ix_material_organization_id'), 'material', ['organization_id'], unique=False)
    op.create_index(op.f('ix_material_plant_id'), 'material', ['plant_id'], unique=False)
    op.create_table('operation_scheduling_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=True),
    sa.Column('default_scheduling_mode', sa.Enum('SEQUENTIAL', 'OVERLAP', 'PARALLEL', name='schedulingmode'), nullable=False),
    sa.Column('default_overlap_percentage', sa.Float(), nullable=False),
    sa.Column('allow_parallel_operations', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('default_overlap_percentage >= 0 AND default_overlap_percentage <= 100', name='check_default_overlap_percentage_range'),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_center.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'work_center_id', name='uq_scheduling_config_per_work_center')
    )
    op.create_index('idx_scheduling_config_org_plant', 'operation_scheduling_config', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_operation_scheduling_config_organization_id'), 'operation_scheduling_config', ['organization_id'], unique=False)
    op.create_index(op.f('ix_operation_scheduling_config_plant_id'), 'operation_scheduling_config', ['plant_id'], unique=False)
    op.create_index(op.f('ix_operation_scheduling_config_work_center_id'), 'operation_scheduling_config', ['work_center_id'], unique=False)
    op.create_table('pm_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('schedule_code', sa.String(length=50), nullable=False),
    sa.Column('schedule_name', sa.String(length=200), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('CALENDAR', 'METER', name='triggertype'), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=True),
    sa.Column('meter_threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(trigger_type = 'CALENDAR' AND frequency_days IS NOT NULL) OR (trigger_type = 'METER' AND meter_threshold IS NOT NULL)", name='check_pm_schedule_trigger_requirements'),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'schedule_code', name='uq_pm_schedule_code_per_plant')
    )
    op.create_index('idx_pm_schedule_active', 'pm_schedule', ['is_active'], unique=False)
    op.create_index('idx_pm_schedule_machine', 'pm_schedule', ['machine_id'], unique=False)
    op.create_index('idx_pm_schedule_org_plant', 'pm_schedule', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_pm_schedule_id'), 'pm_schedule', ['id'], unique=False)
    op.create_index(op.f('ix_pm_schedule_machine_id'), 'pm_schedule', ['machine_id'], unique=False)
    op.create_index(op.f('ix_pm_schedule_organization_id'), 'pm_schedule', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pm_schedule_plant_id'), 'pm_schedule', ['plant_id'], unique=False)
    op.create_index(op.f('ix_pm_schedule_schedule_code'), 'pm_schedule', ['schedule_code'], unique=False)
    op.create_table('shift_handover',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('from_shift_id', sa.Integer(), nullable=False),
    sa.Column('to_shift_id', sa.Integer(), nullable=False),
    sa.Column('handover_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wip_quantity', sa.Float(), nullable=False),
    sa.Column('production_summary', sa.Text(), nullable=False),
    sa.Column('quality_issues', sa.Text(), nullable=True),
    sa.Column('machine_status', sa.Text(), nullable=True),
    sa.Column('material_status', sa.Text(), nullable=True),
    sa.Column('safety_incidents', sa.Text(), nullable=True),
    sa.Column('handover_by_user_id', sa.Integer(), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('from_shift_id != to_shift_id', name='check_different_shifts'),
    sa.CheckConstraint('wip_quantity >= 0', name='check_wip_quantity_non_negative'),
    sa.ForeignKeyConstraint(['from_shift_id'], ['shift.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_shift_id'], ['shift.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shift_handover_date', 'shift_handover', ['handover_date'], unique=False)
    op.create_index('idx_shift_handover_from_shift', 'shift_handover', ['from_shift_id'], unique=False)
    op.create_index('idx_shift_handover_org_plant', 'shift_handover', ['organization_id', 'plant_id'], unique=False)
    op.create_index('idx_shift_handover_to_shift', 'shift_handover', ['to_shift_id'], unique=False)
    op.create_index(op.f('ix_shift_handover_from_shift_id'), 'shift_handover', ['from_shift_id'], unique=False)
    op.create_index(op.f('ix_shift_handover_handover_date'), 'shift_handover', ['handover_date'], unique=False)
    op.create_index(op.f('ix_shift_handover_organization_id'), 'shift_handover', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shift_handover_plant_id'), 'shift_handover', ['plant_id'], unique=False)
    op.create_index(op.f('ix_shift_handover_to_shift_id'), 'shift_handover', ['to_shift_id'], unique=False)
    op.create_table('shift_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('performance_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('production_target', sa.Float(), nullable=False),
    sa.Column('production_actual', sa.Float(), nullable=False),
    sa.Column('target_attainment_percent', sa.Float(), nullable=False),
    sa.Column('availability_percent', sa.Float(), nullable=True),
    sa.Column('performance_percent', sa.Float(), nullable=True),
    sa.Column('quality_percent', sa.Float(), nullable=True),
    sa.Column('oee_percent', sa.Float(), nullable=True),
    sa.Column('total_produced', sa.Float(), nullable=False),
    sa.Column('total_good', sa.Float(), nullable=False),
    sa.Column('total_rejected', sa.Float(), nullable=False),
    sa.Column('fpy_percent', sa.Float(), nullable=True),
    sa.Column('planned_production_time', sa.Float(), nullable=True),
    sa.Column('actual_run_time', sa.Float(), nullable=True),
    sa.Column('downtime_minutes', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('production_actual >= 0', name='check_perf_actual_non_negative'),
    sa.CheckConstraint('production_target >= 0', name='check_perf_target_non_negative'),
    sa.CheckConstraint('target_attainment_percent >= 0', name='check_target_attainment_non_negative'),
    sa.CheckConstraint('total_good >= 0', name='check_total_good_non_negative'),
    sa.CheckConstraint('total_produced >= 0', name='check_total_produced_non_negative'),
    sa.CheckConstraint('total_rejected >= 0', name='check_total_rejected_non_negative'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'shift_id', 'performance_date', name='uq_shift_performance_per_date')
    )
    op.create_index('idx_shift_performance_date', 'shift_performance', ['performance_date'], unique=False)
    op.create_index('idx_shift_performance_org_plant', 'shift_performance', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_shift_performance_organization_id'), 'shift_performance', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shift_performance_performance_date'), 'shift_performance', ['performance_date'], unique=False)
    op.create_index(op.f('ix_shift_performance_plant_id'), 'shift_performance', ['plant_id'], unique=False)
    op.create_index(op.f('ix_shift_performance_shift_id'), 'shift_performance', ['shift_id'], unique=False)
    op.create_table('work_center_shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=50), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('capacity_percentage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('capacity_percentage > 0 AND capacity_percentage <= 200', name='check_capacity_percentage_range'),
    sa.CheckConstraint('shift_number > 0', name='check_shift_number_positive'),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_center.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_center_id', 'shift_number', name='uq_shift_number_per_work_center')
    )
    op.create_index('idx_shift_work_center', 'work_center_shift', ['work_center_id'], unique=False)
    op.create_index('idx_work_center_shift_active', 'work_center_shift', ['is_active'], unique=False)
    op.create_index(op.f('ix_work_center_shift_work_center_id'), 'work_center_shift', ['work_center_id'], unique=False)
    op.create_table('bom_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('bom_number', sa.String(length=50), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('bom_version', sa.Integer(), nullable=False),
    sa.Column('bom_name', sa.String(length=200), nullable=False),
    sa.Column('bom_type', sa.Enum('PRODUCTION', 'ENGINEERING', 'PLANNING', name='bomtype'), nullable=False),
    sa.Column('base_quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=True),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('base_quantity > 0', name='check_base_quantity_positive'),
    sa.CheckConstraint('bom_version >= 1', name='check_bom_version_minimum'),
    sa.CheckConstraint('effective_end_date IS NULL OR effective_start_date IS NULL OR effective_start_date <= effective_end_date', name='check_effective_dates_valid'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'material_id', 'bom_version', name='uq_bom_per_material_version')
    )
    op.create_index('idx_bom_header_bom_number', 'bom_header', ['bom_number'], unique=False)
    op.create_index('idx_bom_header_effectivity', 'bom_header', ['material_id', 'effective_start_date', 'effective_end_date'], unique=False)
    op.create_index('idx_bom_header_material', 'bom_header', ['material_id'], unique=False)
    op.create_index('idx_bom_header_org_plant', 'bom_header', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_bom_header_bom_number'), 'bom_header', ['bom_number'], unique=False)
    op.create_index(op.f('ix_bom_header_effective_start_date'), 'bom_header', ['effective_start_date'], unique=False)
    op.create_index(op.f('ix_bom_header_is_active'), 'bom_header', ['is_active'], unique=False)
    op.create_index(op.f('ix_bom_header_material_id'), 'bom_header', ['material_id'], unique=False)
    op.create_index(op.f('ix_bom_header_organization_id'), 'bom_header', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bom_header_plant_id'), 'bom_header', ['plant_id'], unique=False)
    op.create_table('cost_layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity_received > 0', name='chk_quantity_received_positive'),
    sa.CheckConstraint('quantity_remaining <= quantity_received', name='chk_remaining_not_exceed_received'),
    sa.CheckConstraint('quantity_remaining >= 0', name='chk_quantity_remaining_non_negative'),
    sa.CheckConstraint('unit_cost >= 0', name='chk_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_layer_currency', 'cost_layer', ['currency_code'], unique=False)
    op.create_index('idx_cost_layer_fifo', 'cost_layer', ['material_id', 'receipt_date'], unique=False)
    op.create_index('idx_cost_layer_lifo', 'cost_layer', ['material_id', 'receipt_date'], unique=False)
    op.create_index('idx_cost_layer_material', 'cost_layer', ['material_id'], unique=False)
    op.create_index('idx_cost_layer_org_plant', 'cost_layer', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_cost_layer_currency_code'), 'cost_layer', ['currency_code'], unique=False)
    op.create_index(op.f('ix_cost_layer_id'), 'cost_layer', ['id'], unique=False)
    op.create_index(op.f('ix_cost_layer_material_id'), 'cost_layer', ['material_id'], unique=False)
    op.create_index(op.f('ix_cost_layer_organization_id'), 'cost_layer', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cost_layer_plant_id'), 'cost_layer', ['plant_id'], unique=False)
    op.create_index(op.f('ix_cost_layer_receipt_date'), 'cost_layer', ['receipt_date'], unique=False)
    op.create_index(op.f('ix_cost_layer_storage_location_id'), 'cost_layer', ['storage_location_id'], unique=False)
    op.create_table('inspection_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('inspection_frequency', sa.Enum('PER_LOT', 'PER_SHIFT', 'HOURLY', 'CONTINUOUS', name='inspectionfrequency'), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('sample_size > 0', name='check_inspection_sample_size_positive'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inspection_plan_material', 'inspection_plan', ['material_id'], unique=False)
    op.create_index('idx_inspection_plan_org_plant', 'inspection_plan', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_inspection_plan_material_id'), 'inspection_plan', ['material_id'], unique=False)
    op.create_index(op.f('ix_inspection_plan_organization_id'), 'inspection_plan', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inspection_plan_plant_id'), 'inspection_plan', ['plant_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('quantity_on_hand', sa.Float(), nullable=False),
    sa.Column('quantity_reserved', sa.Float(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.Column('last_movement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity_on_hand >= 0', name='chk_quantity_on_hand_non_negative'),
    sa.CheckConstraint('quantity_reserved <= quantity_on_hand', name='chk_reserved_not_exceed_on_hand'),
    sa.CheckConstraint('quantity_reserved >= 0', name='chk_quantity_reserved_non_negative'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'material_id', 'storage_location_id', 'batch_number', name='uq_inventory_composite')
    )
    op.create_index('idx_inventory_org_plant', 'inventory', ['organization_id', 'plant_id'], unique=False)
    op.create_index('idx_inventory_org_plant_material', 'inventory', ['organization_id', 'plant_id', 'material_id'], unique=False)
    op.create_index('idx_inventory_storage_location', 'inventory', ['storage_location_id'], unique=False)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_material_id'), 'inventory', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventory_organization_id'), 'inventory', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_plant_id'), 'inventory', ['plant_id'], unique=False)
    op.create_index(op.f('ix_inventory_storage_location_id'), 'inventory', ['storage_location_id'], unique=False)
    op.create_table('inventory_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('GOODS_RECEIPT', 'GOODS_ISSUE', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_date', 'inventory_transaction', ['transaction_date'], unique=False)
    op.create_index('idx_transaction_date_type', 'inventory_transaction', ['transaction_date', 'transaction_type'], unique=False)
    op.create_index('idx_transaction_material', 'inventory_transaction', ['material_id'], unique=False)
    op.create_index('idx_transaction_org_plant', 'inventory_transaction', ['organization_id', 'plant_id'], unique=False)
    op.create_index('idx_transaction_type', 'inventory_transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_id'), 'inventory_transaction', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_material_id'), 'inventory_transaction', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_organization_id'), 'inventory_transaction', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_plant_id'), 'inventory_transaction', ['plant_id'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_storage_location_id'), 'inventory_transaction', ['storage_location_id'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_transaction_date'), 'inventory_transaction', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_inventory_transaction_transaction_type'), 'inventory_transaction', ['transaction_type'], unique=False)
    op.create_table('material_costing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('costing_method', sa.Enum('FIFO', 'LIFO', 'WEIGHTED_AVERAGE', 'STANDARD', name='costingmethod'), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('standard_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_average_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('last_cost_update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('current_average_cost >= 0 OR current_average_cost IS NULL', name='chk_avg_cost_non_negative'),
    sa.CheckConstraint('standard_cost >= 0 OR standard_cost IS NULL', name='chk_standard_cost_non_negative'),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'material_id', name='uq_costing_per_material_per_plant')
    )
    op.create_index('idx_material_costing_currency', 'material_costing', ['currency_code'], unique=False)
    op.create_index('idx_material_costing_material', 'material_costing', ['material_id'], unique=False)
    op.create_index('idx_material_costing_org_plant', 'material_costing', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_material_costing_currency_code'), 'material_costing', ['currency_code'], unique=False)
    op.create_index(op.f('ix_material_costing_id'), 'material_costing', ['id'], unique=False)
    op.create_index(op.f('ix_material_costing_material_id'), 'material_costing', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_costing_organization_id'), 'material_costing', ['organization_id'], unique=False)
    op.create_index(op.f('ix_material_costing_plant_id'), 'material_costing', ['plant_id'], unique=False)
    op.create_table('pm_work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('pm_schedule_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('pm_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='pmstatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pm_schedule_id'], ['pm_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'pm_number', name='uq_pm_work_order_number_per_plant')
    )
    op.create_index('idx_pm_work_order_machine', 'pm_work_order', ['machine_id'], unique=False)
    op.create_index('idx_pm_work_order_org_plant', 'pm_work_order', ['organization_id', 'plant_id'], unique=False)
    op.create_index('idx_pm_work_order_schedule', 'pm_work_order', ['pm_schedule_id'], unique=False)
    op.create_index('idx_pm_work_order_scheduled_date', 'pm_work_order', ['scheduled_date'], unique=False)
    op.create_index('idx_pm_work_order_status', 'pm_work_order', ['status'], unique=False)
    op.create_index(op.f('ix_pm_work_order_id'), 'pm_work_order', ['id'], unique=False)
    op.create_index(op.f('ix_pm_work_order_machine_id'), 'pm_work_order', ['machine_id'], unique=False)
    op.create_index(op.f('ix_pm_work_order_organization_id'), 'pm_work_order', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pm_work_order_plant_id'), 'pm_work_order', ['plant_id'], unique=False)
    op.create_index(op.f('ix_pm_work_order_pm_number'), 'pm_work_order', ['pm_number'], unique=False)
    op.create_index(op.f('ix_pm_work_order_pm_schedule_id'), 'pm_work_order', ['pm_schedule_id'], unique=False)
    op.create_index(op.f('ix_pm_work_order_status'), 'pm_work_order', ['status'], unique=False)
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('work_order_number', sa.String(length=50), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('PRODUCTION', 'REWORK', 'ASSEMBLY', name='ordertype'), nullable=False),
    sa.Column('order_status', sa.Enum('PLANNED', 'RELEASED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('planned_quantity', sa.Float(), nullable=False),
    sa.Column('actual_quantity', sa.Float(), nullable=False),
    sa.Column('start_date_planned', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date_planned', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_rework_order', sa.Boolean(), nullable=False),
    sa.Column('parent_work_order_id', sa.Integer(), nullable=True),
    sa.Column('rework_reason_code', sa.String(length=50), nullable=True),
    sa.Column('rework_mode', sa.Enum('CONSUME_ADDITIONAL_MATERIALS', 'REPROCESS_EXISTING_WIP', 'HYBRID', name='reworkmode'), nullable=True),
    sa.CheckConstraint('actual_quantity <= planned_quantity', name='check_actual_not_exceed_planned'),
    sa.CheckConstraint('actual_quantity >= 0', name='check_actual_quantity_non_negative'),
    sa.CheckConstraint('planned_quantity > 0', name='check_planned_quantity_positive'),
    sa.CheckConstraint('priority >= 1 AND priority <= 10', name='check_priority_range'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plant_id', 'work_order_number', name='uq_work_order_number_per_plant')
    )
    op.create_index('idx_work_order_material', 'work_order', ['material_id'], unique=False)
    op.create_index('idx_work_order_org_plant', 'work_order', ['organization_id', 'plant_id'], unique=False)
    op.create_index('idx_work_order_status', 'work_order', ['order_status'], unique=False)
    op.create_index(op.f('ix_work_order_material_id'), 'work_order', ['material_id'], unique=False)
    op.create_index(op.f('ix_work_order_order_status'), 'work_order', ['order_status'], unique=False)
    op.create_index(op.f('ix_work_order_organization_id'), 'work_order', ['organization_id'], unique=False)
    op.create_index(op.f('ix_work_order_parent_work_order_id'), 'work_order', ['parent_work_order_id'], unique=False)
    op.create_index(op.f('ix_work_order_plant_id'), 'work_order', ['plant_id'], unique=False)
    op.create_index(op.f('ix_work_order_work_order_number'), 'work_order', ['work_order_number'], unique=False)
    op.create_table('bom_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_header_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('component_material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.Column('scrap_factor', sa.Float(), nullable=False),
    sa.Column('operation_number', sa.Integer(), nullable=True),
    sa.Column('is_phantom', sa.Boolean(), nullable=False),
    sa.Column('backflush', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('line_number > 0', name='check_line_number_positive'),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.CheckConstraint('scrap_factor >= 0 AND scrap_factor <= 100', name='check_scrap_factor_range'),
    sa.ForeignKeyConstraint(['bom_header_id'], ['bom_header.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_header_id', 'line_number', name='uq_line_number_per_bom')
    )
    op.create_index('idx_bom_line_bom_header', 'bom_line', ['bom_header_id'], unique=False)
    op.create_index('idx_bom_line_component_material', 'bom_line', ['component_material_id'], unique=False)
    op.create_index(op.f('ix_bom_line_bom_header_id'), 'bom_line', ['bom_header_id'], unique=False)
    op.create_index(op.f('ix_bom_line_component_material_id'), 'bom_line', ['component_material_id'], unique=False)
    op.create_table('inspection_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('inspection_plan_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('inspected_quantity', sa.Integer(), nullable=False),
    sa.Column('passed_quantity', sa.Integer(), nullable=False),
    sa.Column('failed_quantity', sa.Integer(), nullable=False),
    sa.Column('inspector_user_id', sa.Integer(), nullable=False),
    sa.Column('inspection_notes', sa.String(length=500), nullable=True),
    sa.Column('measurement_data', sa.JSON(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('failed_quantity >= 0', name='check_inspection_failed_non_negative'),
    sa.CheckConstraint('inspected_quantity > 0', name='check_inspection_inspected_positive'),
    sa.CheckConstraint('passed_quantity + failed_quantity = inspected_quantity', name='check_inspection_quantities_sum'),
    sa.CheckConstraint('passed_quantity >= 0', name='check_inspection_passed_non_negative'),
    sa.ForeignKeyConstraint(['inspection_plan_id'], ['inspection_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inspection_log_org_plant', 'inspection_log', ['organization_id', 'plant_id'], unique=False)
    op.create_index('idx_inspection_log_plan', 'inspection_log', ['inspection_plan_id'], unique=False)
    op.create_index('idx_inspection_log_work_order', 'inspection_log', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_inspection_log_inspection_plan_id'), 'inspection_log', ['inspection_plan_id'], unique=False)
    op.create_index(op.f('ix_inspection_log_organization_id'), 'inspection_log', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inspection_log_plant_id'), 'inspection_log', ['plant_id'], unique=False)
    op.create_index(op.f('ix_inspection_log_work_order_id'), 'inspection_log', ['work_order_id'], unique=False)
    op.create_table('ncr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('ncr_number', sa.String(length=50), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('defect_type', sa.Enum('DIMENSIONAL', 'VISUAL', 'FUNCTIONAL', 'MATERIAL', 'OTHER', name='defecttype'), nullable=False),
    sa.Column('defect_description', sa.String(length=500), nullable=False),
    sa.Column('quantity_defective', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'CLOSED', name='ncrstatus'), nullable=False),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=False),
    sa.Column('attachment_urls', sa.JSON(), nullable=True),
    sa.Column('resolution_notes', sa.String(length=1000), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity_defective > 0', name='check_ncr_quantity_positive'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ncr_org_plant', 'ncr', ['organization_id', 'plant_id'], unique=False)
    op.create_index('idx_ncr_status', 'ncr', ['status'], unique=False)
    op.create_index('idx_ncr_work_order', 'ncr', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_ncr_material_id'), 'ncr', ['material_id'], unique=False)
    op.create_index(op.f('ix_ncr_ncr_number'), 'ncr', ['ncr_number'], unique=False)
    op.create_index(op.f('ix_ncr_organization_id'), 'ncr', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ncr_plant_id'), 'ncr', ['plant_id'], unique=False)
    op.create_index(op.f('ix_ncr_status'), 'ncr', ['status'], unique=False)
    op.create_index(op.f('ix_ncr_work_order_id'), 'ncr', ['work_order_id'], unique=False)
    op.create_table('work_order_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('planned_quantity', sa.Float(), nullable=False),
    sa.Column('actual_quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.Column('backflush', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('actual_quantity >= 0', name='check_wom_actual_quantity_non_negative'),
    sa.CheckConstraint('planned_quantity > 0', name='check_wom_planned_quantity_positive'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measure.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_work_order_material_mat', 'work_order_material', ['material_id'], unique=False)
    op.create_index('idx_work_order_material_wo', 'work_order_material', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_work_order_material_material_id'), 'work_order_material', ['material_id'], unique=False)
    op.create_index(op.f('ix_work_order_material_work_order_id'), 'work_order_material', ['work_order_id'], unique=False)
    op.create_table('work_order_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('operation_number', sa.Integer(), nullable=False),
    sa.Column('operation_name', sa.String(length=100), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=False),
    sa.Column('setup_time_minutes', sa.Float(), nullable=False),
    sa.Column('run_time_per_unit_minutes', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='operationstatus'), nullable=False),
    sa.Column('actual_setup_time', sa.Float(), nullable=True),
    sa.Column('actual_run_time', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduling_mode', sa.Enum('SEQUENTIAL', 'OVERLAP', 'PARALLEL', name='schedulingmode'), nullable=False),
    sa.Column('overlap_percentage', sa.Float(), nullable=False),
    sa.Column('predecessor_operation_id', sa.Integer(), nullable=True),
    sa.Column('can_start_at_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('can_start_at_percentage >= 0 AND can_start_at_percentage <= 100', name='check_can_start_percentage_range'),
    sa.CheckConstraint('operation_number > 0', name='check_operation_number_positive'),
    sa.CheckConstraint('overlap_percentage >= 0 AND overlap_percentage <= 100', name='check_overlap_percentage_range'),
    sa.CheckConstraint('run_time_per_unit_minutes >= 0', name='check_run_time_non_negative'),
    sa.CheckConstraint('setup_time_minutes >= 0', name='check_setup_time_non_negative'),
    sa.ForeignKeyConstraint(['predecessor_operation_id'], ['work_order_operation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_center.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_id', 'operation_number', name='uq_operation_number_per_work_order')
    )
    op.create_index('idx_operation_work_order', 'work_order_operation', ['work_order_id'], unique=False)
    op.create_index('idx_work_order_operation_org_plant', 'work_order_operation', ['organization_id', 'plant_id'], unique=False)
    op.create_index(op.f('ix_work_order_operation_organization_id'), 'work_order_operation', ['organization_id'], unique=False)
    op.create_index(op.f('ix_work_order_operation_plant_id'), 'work_order_operation', ['plant_id'], unique=False)
    op.create_index(op.f('ix_work_order_operation_work_order_id'), 'work_order_operation', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_operation_work_order_id'), table_name='work_order_operation')
    op.drop_index(op.f('ix_work_order_operation_plant_id'), table_name='work_order_operation')
    op.drop_index(op.f('ix_work_order_operation_organization_id'), table_name='work_order_operation')
    op.drop_index('idx_work_order_operation_org_plant', table_name='work_order_operation')
    op.drop_index('idx_operation_work_order', table_name='work_order_operation')
    op.drop_table('work_order_operation')
    op.drop_index(op.f('ix_work_order_material_work_order_id'), table_name='work_order_material')
    op.drop_index(op.f('ix_work_order_material_material_id'), table_name='work_order_material')
    op.drop_index('idx_work_order_material_wo', table_name='work_order_material')
    op.drop_index('idx_work_order_material_mat', table_name='work_order_material')
    op.drop_table('work_order_material')
    op.drop_index(op.f('ix_ncr_work_order_id'), table_name='ncr')
    op.drop_index(op.f('ix_ncr_status'), table_name='ncr')
    op.drop_index(op.f('ix_ncr_plant_id'), table_name='ncr')
    op.drop_index(op.f('ix_ncr_organization_id'), table_name='ncr')
    op.drop_index(op.f('ix_ncr_ncr_number'), table_name='ncr')
    op.drop_index(op.f('ix_ncr_material_id'), table_name='ncr')
    op.drop_index('idx_ncr_work_order', table_name='ncr')
    op.drop_index('idx_ncr_status', table_name='ncr')
    op.drop_index('idx_ncr_org_plant', table_name='ncr')
    op.drop_table('ncr')
    op.drop_index(op.f('ix_inspection_log_work_order_id'), table_name='inspection_log')
    op.drop_index(op.f('ix_inspection_log_plant_id'), table_name='inspection_log')
    op.drop_index(op.f('ix_inspection_log_organization_id'), table_name='inspection_log')
    op.drop_index(op.f('ix_inspection_log_inspection_plan_id'), table_name='inspection_log')
    op.drop_index('idx_inspection_log_work_order', table_name='inspection_log')
    op.drop_index('idx_inspection_log_plan', table_name='inspection_log')
    op.drop_index('idx_inspection_log_org_plant', table_name='inspection_log')
    op.drop_table('inspection_log')
    op.drop_index(op.f('ix_bom_line_component_material_id'), table_name='bom_line')
    op.drop_index(op.f('ix_bom_line_bom_header_id'), table_name='bom_line')
    op.drop_index('idx_bom_line_component_material', table_name='bom_line')
    op.drop_index('idx_bom_line_bom_header', table_name='bom_line')
    op.drop_table('bom_line')
    op.drop_index(op.f('ix_work_order_work_order_number'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_plant_id'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_parent_work_order_id'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_organization_id'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_order_status'), table_name='work_order')
    op.drop_index(op.f('ix_work_order_material_id'), table_name='work_order')
    op.drop_index('idx_work_order_status', table_name='work_order')
    op.drop_index('idx_work_order_org_plant', table_name='work_order')
    op.drop_index('idx_work_order_material', table_name='work_order')
    op.drop_table('work_order')
    op.drop_index(op.f('ix_pm_work_order_status'), table_name='pm_work_order')
    op.drop_index(op.f('ix_pm_work_order_pm_schedule_id'), table_name='pm_work_order')
    op.drop_index(op.f('ix_pm_work_order_pm_number'), table_name='pm_work_order')
    op.drop_index(op.f('ix_pm_work_order_plant_id'), table_name='pm_work_order')
    op.drop_index(op.f('ix_pm_work_order_organization_id'), table_name='pm_work_order')
    op.drop_index(op.f('ix_pm_work_order_machine_id'), table_name='pm_work_order')
    op.drop_index(op.f('ix_pm_work_order_id'), table_name='pm_work_order')
    op.drop_index('idx_pm_work_order_status', table_name='pm_work_order')
    op.drop_index('idx_pm_work_order_scheduled_date', table_name='pm_work_order')
    op.drop_index('idx_pm_work_order_schedule', table_name='pm_work_order')
    op.drop_index('idx_pm_work_order_org_plant', table_name='pm_work_order')
    op.drop_index('idx_pm_work_order_machine', table_name='pm_work_order')
    op.drop_table('pm_work_order')
    op.drop_index(op.f('ix_material_costing_plant_id'), table_name='material_costing')
    op.drop_index(op.f('ix_material_costing_organization_id'), table_name='material_costing')
    op.drop_index(op.f('ix_material_costing_material_id'), table_name='material_costing')
    op.drop_index(op.f('ix_material_costing_id'), table_name='material_costing')
    op.drop_index(op.f('ix_material_costing_currency_code'), table_name='material_costing')
    op.drop_index('idx_material_costing_org_plant', table_name='material_costing')
    op.drop_index('idx_material_costing_material', table_name='material_costing')
    op.drop_index('idx_material_costing_currency', table_name='material_costing')
    op.drop_table('material_costing')
    op.drop_index(op.f('ix_inventory_transaction_transaction_type'), table_name='inventory_transaction')
    op.drop_index(op.f('ix_inventory_transaction_transaction_date'), table_name='inventory_transaction')
    op.drop_index(op.f('ix_inventory_transaction_storage_location_id'), table_name='inventory_transaction')
    op.drop_index(op.f('ix_inventory_transaction_plant_id'), table_name='inventory_transaction')
    op.drop_index(op.f('ix_inventory_transaction_organization_id'), table_name='inventory_transaction')
    op.drop_index(op.f('ix_inventory_transaction_material_id'), table_name='inventory_transaction')
    op.drop_index(op.f('ix_inventory_transaction_id'), table_name='inventory_transaction')
    op.drop_index('idx_transaction_type', table_name='inventory_transaction')
    op.drop_index('idx_transaction_org_plant', table_name='inventory_transaction')
    op.drop_index('idx_transaction_material', table_name='inventory_transaction')
    op.drop_index('idx_transaction_date_type', table_name='inventory_transaction')
    op.drop_index('idx_transaction_date', table_name='inventory_transaction')
    op.drop_table('inventory_transaction')
    op.drop_index(op.f('ix_inventory_storage_location_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_plant_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_organization_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_material_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_index('idx_inventory_storage_location', table_name='inventory')
    op.drop_index('idx_inventory_org_plant_material', table_name='inventory')
    op.drop_index('idx_inventory_org_plant', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_inspection_plan_plant_id'), table_name='inspection_plan')
    op.drop_index(op.f('ix_inspection_plan_organization_id'), table_name='inspection_plan')
    op.drop_index(op.f('ix_inspection_plan_material_id'), table_name='inspection_plan')
    op.drop_index('idx_inspection_plan_org_plant', table_name='inspection_plan')
    op.drop_index('idx_inspection_plan_material', table_name='inspection_plan')
    op.drop_table('inspection_plan')
    op.drop_index(op.f('ix_cost_layer_storage_location_id'), table_name='cost_layer')
    op.drop_index(op.f('ix_cost_layer_receipt_date'), table_name='cost_layer')
    op.drop_index(op.f('ix_cost_layer_plant_id'), table_name='cost_layer')
    op.drop_index(op.f('ix_cost_layer_organization_id'), table_name='cost_layer')
    op.drop_index(op.f('ix_cost_layer_material_id'), table_name='cost_layer')
    op.drop_index(op.f('ix_cost_layer_id'), table_name='cost_layer')
    op.drop_index(op.f('ix_cost_layer_currency_code'), table_name='cost_layer')
    op.drop_index('idx_cost_layer_org_plant', table_name='cost_layer')
    op.drop_index('idx_cost_layer_material', table_name='cost_layer')
    op.drop_index('idx_cost_layer_lifo', table_name='cost_layer')
    op.drop_index('idx_cost_layer_fifo', table_name='cost_layer')
    op.drop_index('idx_cost_layer_currency', table_name='cost_layer')
    op.drop_table('cost_layer')
    op.drop_index(op.f('ix_bom_header_plant_id'), table_name='bom_header')
    op.drop_index(op.f('ix_bom_header_organization_id'), table_name='bom_header')
    op.drop_index(op.f('ix_bom_header_material_id'), table_name='bom_header')
    op.drop_index(op.f('ix_bom_header_is_active'), table_name='bom_header')
    op.drop_index(op.f('ix_bom_header_effective_start_date'), table_name='bom_header')
    op.drop_index(op.f('ix_bom_header_bom_number'), table_name='bom_header')
    op.drop_index('idx_bom_header_org_plant', table_name='bom_header')
    op.drop_index('idx_bom_header_material', table_name='bom_header')
    op.drop_index('idx_bom_header_effectivity', table_name='bom_header')
    op.drop_index('idx_bom_header_bom_number', table_name='bom_header')
    op.drop_table('bom_header')
    op.drop_index(op.f('ix_work_center_shift_work_center_id'), table_name='work_center_shift')
    op.drop_index('idx_work_center_shift_active', table_name='work_center_shift')
    op.drop_index('idx_shift_work_center', table_name='work_center_shift')
    op.drop_table('work_center_shift')
    op.drop_index(op.f('ix_shift_performance_shift_id'), table_name='shift_performance')
    op.drop_index(op.f('ix_shift_performance_plant_id'), table_name='shift_performance')
    op.drop_index(op.f('ix_shift_performance_performance_date'), table_name='shift_performance')
    op.drop_index(op.f('ix_shift_performance_organization_id'), table_name='shift_performance')
    op.drop_index('idx_shift_performance_org_plant', table_name='shift_performance')
    op.drop_index('idx_shift_performance_date', table_name='shift_performance')
    op.drop_table('shift_performance')
    op.drop_index(op.f('ix_shift_handover_to_shift_id'), table_name='shift_handover')
    op.drop_index(op.f('ix_shift_handover_plant_id'), table_name='shift_handover')
    op.drop_index(op.f('ix_shift_handover_organization_id'), table_name='shift_handover')
    op.drop_index(op.f('ix_shift_handover_handover_date'), table_name='shift_handover')
    op.drop_index(op.f('ix_shift_handover_from_shift_id'), table_name='shift_handover')
    op.drop_index('idx_shift_handover_to_shift', table_name='shift_handover')
    op.drop_index('idx_shift_handover_org_plant', table_name='shift_handover')
    op.drop_index('idx_shift_handover_from_shift', table_name='shift_handover')
    op.drop_index('idx_shift_handover_date', table_name='shift_handover')
    op.drop_table('shift_handover')
    op.drop_index(op.f('ix_pm_schedule_schedule_code'), table_name='pm_schedule')
    op.drop_index(op.f('ix_pm_schedule_plant_id'), table_name='pm_schedule')
    op.drop_index(op.f('ix_pm_schedule_organization_id'), table_name='pm_schedule')
    op.drop_index(op.f('ix_pm_schedule_machine_id'), table_name='pm_schedule')
    op.drop_index(op.f('ix_pm_schedule_id'), table_name='pm_schedule')
    op.drop_index('idx_pm_schedule_org_plant', table_name='pm_schedule')
    op.drop_index('idx_pm_schedule_machine', table_name='pm_schedule')
    op.drop_index('idx_pm_schedule_active', table_name='pm_schedule')
    op.drop_table('pm_schedule')
    op.drop_index(op.f('ix_operation_scheduling_config_work_center_id'), table_name='operation_scheduling_config')
    op.drop_index(op.f('ix_operation_scheduling_config_plant_id'), table_name='operation_scheduling_config')
    op.drop_index(op.f('ix_operation_scheduling_config_organization_id'), table_name='operation_scheduling_config')
    op.drop_index('idx_scheduling_config_org_plant', table_name='operation_scheduling_config')
    op.drop_table('operation_scheduling_config')
    op.drop_index(op.f('ix_material_plant_id'), table_name='material')
    op.drop_index(op.f('ix_material_organization_id'), table_name='material')
    op.drop_index(op.f('ix_material_material_number'), table_name='material')
    op.drop_index(op.f('ix_material_id'), table_name='material')
    op.drop_index('idx_material_org_plant', table_name='material')
    op.drop_index('idx_material_number', table_name='material')
    op.drop_index('idx_material_category', table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_machine_status_history_started_at'), table_name='machine_status_history')
    op.drop_index(op.f('ix_machine_status_history_machine_id'), table_name='machine_status_history')
    op.drop_index(op.f('ix_machine_status_history_id'), table_name='machine_status_history')
    op.drop_index(op.f('ix_machine_status_history_ended_at'), table_name='machine_status_history')
    op.drop_index('idx_machine_status_history_time_range', table_name='machine_status_history')
    op.drop_index('idx_machine_status_history_machine_time', table_name='machine_status_history')
    op.drop_table('machine_status_history')
    op.drop_index(op.f('ix_exchange_rate_to_currency_code'), table_name='exchange_rate')
    op.drop_index(op.f('ix_exchange_rate_id'), table_name='exchange_rate')
    op.drop_index(op.f('ix_exchange_rate_from_currency_code'), table_name='exchange_rate')
    op.drop_index(op.f('ix_exchange_rate_effective_date'), table_name='exchange_rate')
    op.drop_index('idx_exchange_rate_lookup', table_name='exchange_rate')
    op.drop_index('idx_exchange_rate_effective_date', table_name='exchange_rate')
    op.drop_index('idx_exchange_rate_currencies', table_name='exchange_rate')
    op.drop_table('exchange_rate')
    op.drop_index(op.f('ix_downtime_event_started_at'), table_name='downtime_event')
    op.drop_index(op.f('ix_downtime_event_plant_id'), table_name='downtime_event')
    op.drop_index(op.f('ix_downtime_event_organization_id'), table_name='downtime_event')
    op.drop_index(op.f('ix_downtime_event_machine_id'), table_name='downtime_event')
    op.drop_index(op.f('ix_downtime_event_id'), table_name='downtime_event')
    op.drop_index(op.f('ix_downtime_event_ended_at'), table_name='downtime_event')
    op.drop_index(op.f('ix_downtime_event_category'), table_name='downtime_event')
    op.drop_index('idx_downtime_event_time_range', table_name='downtime_event')
    op.drop_index('idx_downtime_event_org_plant', table_name='downtime_event')
    op.drop_index('idx_downtime_event_machine_time', table_name='downtime_event')
    op.drop_index('idx_downtime_event_machine', table_name='downtime_event')
    op.drop_index('idx_downtime_event_category', table_name='downtime_event')
    op.drop_table('downtime_event')
    op.drop_index(op.f('ix_work_center_work_center_code'), table_name='work_center')
    op.drop_index(op.f('ix_work_center_plant_id'), table_name='work_center')
    op.drop_index(op.f('ix_work_center_organization_id'), table_name='work_center')
    op.drop_index('idx_work_center_org_plant', table_name='work_center')
    op.drop_table('work_center')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_unit_of_measure_uom_code'), table_name='unit_of_measure')
    op.drop_index(op.f('ix_unit_of_measure_id'), table_name='unit_of_measure')
    op.drop_table('unit_of_measure')
    op.drop_index(op.f('ix_storage_location_plant_id'), table_name='storage_location')
    op.drop_index(op.f('ix_storage_location_organization_id'), table_name='storage_location')
    op.drop_index(op.f('ix_storage_location_location_code'), table_name='storage_location')
    op.drop_index(op.f('ix_storage_location_id'), table_name='storage_location')
    op.drop_index('idx_storage_location_org_plant', table_name='storage_location')
    op.drop_table('storage_location')
    op.drop_index(op.f('ix_shift_shift_code'), table_name='shift')
    op.drop_index(op.f('ix_shift_plant_id'), table_name='shift')
    op.drop_index(op.f('ix_shift_organization_id'), table_name='shift')
    op.drop_index('idx_shift_org_plant', table_name='shift')
    op.drop_index('idx_shift_active', table_name='shift')
    op.drop_table('shift')
    op.drop_index(op.f('ix_rework_config_plant_id'), table_name='rework_config')
    op.drop_index(op.f('ix_rework_config_organization_id'), table_name='rework_config')
    op.drop_index('idx_rework_config_org_plant', table_name='rework_config')
    op.drop_table('rework_config')
    op.drop_index(op.f('ix_material_category_organization_id'), table_name='material_category')
    op.drop_index(op.f('ix_material_category_id'), table_name='material_category')
    op.drop_index(op.f('ix_material_category_category_code'), table_name='material_category')
    op.drop_index('idx_material_category_org_code', table_name='material_category')
    op.drop_table('material_category')
    op.drop_index(op.f('ix_machine_work_center_id'), table_name='machine')
    op.drop_index(op.f('ix_machine_plant_id'), table_name='machine')
    op.drop_index(op.f('ix_machine_organization_id'), table_name='machine')
    op.drop_index(op.f('ix_machine_machine_code'), table_name='machine')
    op.drop_index(op.f('ix_machine_id'), table_name='machine')
    op.drop_index('idx_machine_work_center', table_name='machine')
    op.drop_index('idx_machine_status', table_name='machine')
    op.drop_index('idx_machine_org_plant', table_name='machine')
    op.drop_table('machine')
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_index('idx_currency_code', table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
