"""Add production_logs TimescaleDB hypertable

Revision ID: e23072a55c9e
Revises: 3c7d9e4f1b2a
Create Date: 2025-11-09 13:19:12.262651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e23072a55c9e'
down_revision = '3c7d9e4f1b2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_scrapped', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_reworked', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('quantity_produced >= 0 AND quantity_scrapped >= 0 AND quantity_reworked >= 0', name='check_quantities'),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['work_order_operation.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'timestamp')
    )
    op.create_index('idx_prod_log_machine_time', 'production_logs', ['machine_id', 'timestamp'], unique=False, postgresql_where=sa.text('machine_id IS NOT NULL'))
    op.create_index('idx_prod_log_operator_time', 'production_logs', ['operator_id', 'timestamp'], unique=False, postgresql_where=sa.text('operator_id IS NOT NULL'))
    op.create_index('idx_prod_log_org_time', 'production_logs', ['organization_id', 'timestamp'], unique=False)
    op.create_index('idx_prod_log_plant_time', 'production_logs', ['plant_id', 'timestamp'], unique=False)
    op.create_index('idx_prod_log_wo', 'production_logs', ['work_order_id'], unique=False)

    # Ensure TimescaleDB extension is enabled
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb;")

    # Convert to TimescaleDB hypertable with 1-day chunk intervals
    op.execute("""
        SELECT create_hypertable('production_logs', 'timestamp', chunk_time_interval => INTERVAL '1 day');
    """)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('projects', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'),
               server_default=sa.text("'PLANNING'::projectstatus"),
               existing_nullable=False)
    op.drop_index('idx_prod_log_wo', table_name='production_logs')
    op.drop_index('idx_prod_log_plant_time', table_name='production_logs')
    op.drop_index('idx_prod_log_org_time', table_name='production_logs')
    op.drop_index('idx_prod_log_operator_time', table_name='production_logs', postgresql_where=sa.text('operator_id IS NOT NULL'))
    op.drop_index('idx_prod_log_machine_time', table_name='production_logs', postgresql_where=sa.text('machine_id IS NOT NULL'))
    op.drop_table('production_logs')
    # ### end Alembic commands ###
